In [289]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [290]:
df = pd.read_csv(r'C:\Users\Rahul Paul\OneDrive\Desktop\dataset\dataset 1.csv')
print(df)

      Age  Gender                         Stream  Internships  CGPA  Hostel  \
0      22    Male  Electronics And Communication            1     8       1
1      21  Female               Computer Science            0     7       1
2      22  Female         Information Technology            1     6       0
3      21    Male         Information Technology            0     8       0
4      22    Male                     Mechanical            0     8       1
...   ...     ...                            ...          ...   ...     ...
2961   23    Male         Information Technology            0     7       0
2962   23    Male                     Mechanical            1     7       1
2963   22    Male         Information Technology            1     7       0
2964   22    Male               Computer Science            1     7       0
2965   23    Male                          Civil            0     8       0

      HistoryOfBacklogs  PlacedOrNot
0                     1            1
1                     1            1
2                     0            1
3                     1            1
4                     0            1
...                 ...          ...
2961                  0            0
2962                  0            0
2963                  0            0
2964                  0            0
2965                  0            1

[2966 rows x 8 columns]

In [291]:
df.head()

,Age,Gender,Stream,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot
0,22,Male,Electronics And Communication,1,8,1,1,1
1,21,Female,Computer Science,0,7,1,1,1
2,22,Female,Information Technology,1,6,0,0,1
3,21,Male,Information Technology,0,8,0,1,1
4,22,Male,Mechanical,0,8,1,0,1

In [292]:
df.shape

(2966, 8)

In [293]:
df['Hostel'].replace({1:'Yes',0:'No'},inplace=True)
df

,Age,Gender,Stream,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot
0,22,Male,Electronics And Communication,1,8,Yes,1,1
1,21,Female,Computer Science,0,7,Yes,1,1
2,22,Female,Information Technology,1,6,No,0,1
3,21,Male,Information Technology,0,8,No,1,1
4,22,Male,Mechanical,0,8,Yes,0,1
...,...,...,...,...,...,...,...,...
2961,23,Male,Information Technology,0,7,No,0,0
2962,23,Male,Mechanical,1,7,Yes,0,0
2963,22,Male,Information Technology,1,7,No,0,0
2964,22,Male,Computer Science,1,7,No,0,0
2965,23,Male,Civil,0,8,No,0,1

In [294]:
df['HistoryOfBacklogs'].replace({1:'Yes',0:'No'},inplace=True)
df

,Age,Gender,Stream,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot
0,22,Male,Electronics And Communication,1,8,Yes,Yes,1
1,21,Female,Computer Science,0,7,Yes,Yes,1
2,22,Female,Information Technology,1,6,No,No,1
3,21,Male,Information Technology,0,8,No,Yes,1
4,22,Male,Mechanical,0,8,Yes,No,1
...,...,...,...,...,...,...,...,...
2961,23,Male,Information Technology,0,7,No,No,0
2962,23,Male,Mechanical,1,7,Yes,No,0
2963,22,Male,Information Technology,1,7,No,No,0
2964,22,Male,Computer Science,1,7,No,No,0
2965,23,Male,Civil,0,8,No,No,1

In [295]:
df['CGPA'] = df['CGPA'].astype(float) 
df

,Age,Gender,Stream,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot
0,22,Male,Electronics And Communication,1,8.0,Yes,Yes,1
1,21,Female,Computer Science,0,7.0,Yes,Yes,1
2,22,Female,Information Technology,1,6.0,No,No,1
3,21,Male,Information Technology,0,8.0,No,Yes,1
4,22,Male,Mechanical,0,8.0,Yes,No,1
...,...,...,...,...,...,...,...,...
2961,23,Male,Information Technology,0,7.0,No,No,0
2962,23,Male,Mechanical,1,7.0,Yes,No,0
2963,22,Male,Information Technology,1,7.0,No,No,0
2964,22,Male,Computer Science,1,7.0,No,No,0
2965,23,Male,Civil,0,8.0,No,No,1

In [296]:
print(df.dtypes)

Age                    int64
Gender                object
Stream                object
Internships            int64
CGPA                 float64
Hostel                object
HistoryOfBacklogs     object
PlacedOrNot            int64
dtype: object

In [297]:
df.to_csv('Cleaned_Dataset 1.csv')

In [298]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2966 entries, 0 to 2965
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                2966 non-null   int64
 1   Gender             2966 non-null   object
 2   Stream             2966 non-null   object
 3   Internships        2966 non-null   int64
 4   CGPA               2966 non-null   float64
 5   Hostel             2966 non-null   object
 6   HistoryOfBacklogs  2966 non-null   object
 7   PlacedOrNot        2966 non-null   int64
dtypes: float64(1), int64(3), object(4)
memory usage: 185.5+ KB

In [299]:
Y = df['PlacedOrNot']
X = df.drop(['PlacedOrNot'],axis=1)

In [300]:
X

,Age,Gender,Stream,Internships,CGPA,Hostel,HistoryOfBacklogs
0,22,Male,Electronics And Communication,1,8.0,Yes,Yes
1,21,Female,Computer Science,0,7.0,Yes,Yes
2,22,Female,Information Technology,1,6.0,No,No
3,21,Male,Information Technology,0,8.0,No,Yes
4,22,Male,Mechanical,0,8.0,Yes,No
...,...,...,...,...,...,...,...
2961,23,Male,Information Technology,0,7.0,No,No
2962,23,Male,Mechanical,1,7.0,Yes,No
2963,22,Male,Information Technology,1,7.0,No,No
2964,22,Male,Computer Science,1,7.0,No,No
2965,23,Male,Civil,0,8.0,No,No

In [301]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)

In [302]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier  
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [303]:
ohe = OneHotEncoder()
ohe.fit(X[['Gender','Stream','Hostel','HistoryOfBacklogs']])

OneHotEncoder()

In [304]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['Gender','Stream','Hostel','HistoryOfBacklogs']),
                                    remainder='passthrough')

In [305]:
classifier = RandomForestClassifier(n_estimators=500, max_depth=20, min_samples_split= 5, min_samples_leaf= 2 , max_features='sqrt', class_weight='balanced', random_state=42)

In [306]:
pipe=make_pipeline(column_trans,classifier)

In [307]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Female', 'Male'], dtype=object),
                                                                            array(['Civil', 'Computer Science', 'Electrical',
       'Electronics And Communication', 'Information Technology',
       'Mechanical'], dtype=object),
                                                                            array(['No', 'Yes'], dtype=object),
                                                                            array(['No', 'Yes'], dtype=object)]),
                                                  ['Gender', 'Stream', 'Hostel',
                                                   'HistoryOfBacklogs'])])),
                ('randomforestclassifier',
                 RandomForestClassifier(class_weight='balanced', max_depth=20,
                                        min_samples_leaf=2, min_samples_split=5,
                                        n_estimators=500, random_state=42))])

In [308]:
Y_pred=pipe.predict(X_test)

In [309]:
print("Accuracy: ",accuracy_score(Y_test,Y_pred))

Accuracy:  0.9225589225589226

In [310]:
new_data = pd.DataFrame({
    'Age':22,
    'Gender': "Male",
    'Stream': "Electronics And Communication",
    'Internships': 1,
    'CGPA': 8.0,
    'Hostel': "No",
    'HistoryOfBacklogs': "No",
},index=[0])

In [311]:
p= pipe.predict(new_data)
prob= pipe.predict_proba(new_data)
if p==1:
    print('Placed')
    print(f"You will be placed with probability of {prob[0][1]:.2f}")
else:
    print('Not placed')

Placed
You will be placed with probability of 0.99

In [313]:
import pickle
pickle.dump(pipe,open('model.pkl','wb'))